### ISSUE TITLE
all auth systems report an error

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/auth#116]
so much stuff throws errors:
- email auth kills the server
- google & github auth throw 502 errors via CF
- replit auth says: ![image](https://user-images.githubusercontent.com/68466727/126899103-eba1c1b9-70e7-44cd-9c8c-10ef2cbc1687.png)
- scratch auth is broken and has been for ages, we should just scrap the code and rewrite it, after all we are working on 2.0 but we can make breaking changes so 🤷🏻

**Comment by RedGuy12** [comment]
This is because we still use Replit DB but we aren't on Replit anymore.

**Comment by wgyt** [comment]
Oh yeah, once you get time, can you fast track the transition to mongodb?
