### ISSUE TITLE
The replit auth page looks weird

### ISSUE THREAD

**Issue by RedGuy12** [onedotprojects/auth#118]
# The replit auth page looks weird

## Describe the bug

The page looks weird because
1. it is emptyish
2. there is not much text
3. most of the text is center-aligned but one part is left-aligned

## To Reproduce

Go to https://auth.onedot.cf/auth/replit?url=%2F

## Expected behavior

It should look nice

## Screenshots

![image](https://user-images.githubusercontent.com/61329810/127745368-c05749c2-ab0b-4440-8a70-05c9ec634fc1.png)

## Device info

Not applicable.

## Additional information, if any

Look into the possibility of using an `iframe` instead of a popup.

**Comment by wgyt** [comment]
We used to have an iframe for repl aith

**Comment by RedGuy12** [comment]
That's right we did...I don't remember why we switched to a pop-up...



________________________________

**Comment by wgyt** [comment]
> That's right we did...I don't remember why we switched to a pop-up...
> […](#)

You where the one who did that…

**Comment by retronbv** [comment]
lmfao

**Comment by RedGuy12** [comment]
i can't get iframe to work sadly

but what does work is having it open a new tab

**Comment by RedGuy12** [comment]
good news: it supports jwt

bad news: i can't manually specify a redirect URL: it always goes to `/__replauth`
also no `state` parameter

**Comment by RedGuy12** [comment]
it will be spoofable tho

will be fixed by #34
