### ISSUE TITLE
pig latin

### ISSUE THREAD

**Issue by retronbv** [onedotprojects/auth#128]
## Describe the feature

Piglatin

## Reasons to add this feature

its piglatin (also made by me so its 1000% cool)

## Alternatives to this feature

no piglatin, retronbv very sad

## Additional information, if any

PIGLATIN

---

![image](https://user-images.githubusercontent.com/49005044/127913682-b8e7eb4e-3cfa-43c3-b504-79c6a5f376af.png)

---

## Escribeday ethay eaturefay

Igpay atinlay

## Easonsray otay addyay histay eaturefay

itsyay igpay atinlay (alsoyay ademay ybay emay osay itsyay 1000% oolcay)

## Alternativesyay otay histay eaturefay

onay igpay atinlay, retronbv eryvay adsay

## Additionalyay informationyay, ifyay anyyay

IGPAY ATINLAY

**Comment by RedGuy12** [comment]
i thought about this and decided against it. tx doesn't support it so you'd have to upload the translations straight to the repo. but then it'd be very hard to track strings that need retranslation when the source is updated.

sorry

**Comment by wgyt** [comment]
in theory, we could get TX to add pig latin 

in reality, we can’t

**Comment by retronbv** [comment]
> in theory, we could get TX to add pig latin 
> 
> 
> 
> in reality, we can’t 

So?? Pig Latin needs to be added. I will maintain it in the source if someone reminds me every update 😁

**Comment by wgyt** [comment]
> > in theory, we could get TX to add pig latin
> > in reality, we can’t
> 
> So?? Pig Latin needs to be added. I will maintain it in the source if someone reminds me every update 😁

Just make a PR and I'll express feedback there, I think I could also maintain this.

**Comment by RedGuy12** [comment]
idea: maybe we can have the pig latin auto-generated at runtime?

**Comment by wgyt** [comment]
I think so, @retronbv knows how pig latin works and could make a npm module for doing this

**Comment by retronbv** [comment]
:thonk:

**Comment by RedGuy12** [comment]
> I think so, @retronbv knows how pig latin works and could make a npm module for doing this

(actually I know more about it)

**Comment by RedGuy12** [comment]
added `LOLCAT English` on TX. will repurpose as pig latin.
