### ISSUE TITLE
Invite to Organization

### ISSUE THREAD

**Issue by devxan** [onedotprojects/auth#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none does.

### Describe the feature

Please invite me to the organization.

### Reasons to add this feature

This feature would be good because… I was part of it in the past and was good at designing the branding.

### Alternatives to this feature

N/A

### Anything else?

Make a Xan happy.

### Agree to our policies

- [X] I agree to follow the [Code of Conduct](https://github.com/onedotprojects/auth/blob/issues/.github/CODE_OF_CONDUCT.md).
- [X] I agree to follow the [Contributing Guidelines](https://github.com/onedotprojects/auth/blob/issues/.github/CONTRIBUTING.md).
- [ ] I am willing to submit a PR to add this (optional).

**Comment by devxan** [comment]
@wgyt You should look at this.

**Comment by RedGuy12** [comment]
i already did lol

**Comment by RedGuy12** [comment]
@all-contributors add @devxan for business

**Comment by wgyt** [comment]
Lol, next time, ask on discord

**Comment by wgyt** [comment]
@all-contributors add @devxan for design
