### ISSUE TITLE
Use GH releases and tags instead of develop/release branches

### ISSUE THREAD

**Issue by RedGuy12** [onedotprojects/auth#221]

**Comment by thecrewmate876** [comment]
will require a lot of changing, so i will ask @wgyt

**Comment by thecrewmate876** [comment]
also @onedotprojects/developers please vote if you want this change

**Comment by RedGuy12** [comment]
*I* am the one who has to deal with all this, not William. Releases will be much easier.


________________________________

**Comment by wgyt** [comment]
> will require a lot of changing, so i will ask @wgyt

@RedGuy12 does most of the work, so if it works, and i can do it, i approve

> also @onedotprojects/developers please vote if you want this change

don't ping everyone

> *I* am the one who has to deal with all this, not William. Releases will be much easier.

this is true
