### ISSUE TITLE
migrate scratch auth to new auth system

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/auth#25]
# migrate scratch auth to new auth system
## Describe the feature
we should migrate scratch auth to the new modular auth system
## Reasons to implement this feature
- Easy to do
- The more modular 1Auth is the better
## Alternatives to this feature
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;none
## Additional context

none

**Comment by RedGuy12** [comment]
I am doing this. I already made sure Google and Replit weren't broken after the migration, now I'm checking email. Then I'll move over GitHub and Scratch
________________________________
From: William Horning ***@***.***>
Sent: Wednesday, May 5, 2021 6:56:16 AM
To: onedotprojects/auth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onedotprojects/auth] migrate scratch auth to new auth system (#25)


migrate scratch auth to new auth system
Describe the feature

we should migrate scratch auth to the new modular auth system

Reasons to implement this feature

  *   Easy to do
  *   The more modular 1Auth is the better

Alternatives to this feature

                none

Additional context

none

**Comment by wgyt** [comment]
as far as I know I finished this?
