### ISSUE TITLE
implement `nonce`s

### ISSUE THREAD

**Issue by RedGuy12** [onedotprojects/auth#34]
how it works:
generate nonce (retronid).
replace `{{nonce}}` in the url with the nonce.
save the nonce in a cookie.
add `nonce` parameter to `sendResponse`.
verify the nonce is still the same.

to think about:
privacy concerns?
github, google have nonce systems built in we can use
replit and email stay on our domain
scratch ~would need a system implemented~ supports parameters in the url

i will do this after l10n system

**Comment by RedGuy12** [comment]
Replit auth is currently spoofable. I need to implement this to fix that.

**Comment by wgyt** [comment]
> Replit auth is currently spoofable. I need to implement this to fix that.

Is this in progress?

**Comment by RedGuy12** [comment]
in https://github.com/onedotprojects/auth/commit/a2c105c698c1cc878d7586d031b4c8c3daddcb6d i started using mustache for url rendering. that will make it a bit easier to add nonces
