### ISSUE TITLE
add webauthn

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/auth#39]
# _add webauthn_

## Describe the feature

Add webauthn to oneauth

## Reasons to add this feature

This feature would be good because it is an easy way to login, using touch id, face id, pin, or a hardware key

## Alternatives to this feature

Login via 2fa code

## Additional information, if any

https://webauthn.guide/#registration

**Comment by RedGuy12** [comment]
@wgyt or others, fee free to do this

**Comment by wgyt** [comment]
Would be useful for #15
