### ISSUE TITLE
Logo doesn’t display 

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/auth#61]
Brand assets need the /brand/ prefix when using 1CDN due to 1CDN removing unnecessary changes making it look for files in the cdn/brand folder even though that isn’t right.

**Comment by wgyt** [comment]
@RedGuy12 all we need to do is add /brand/ to all of our requests to 1CDN. For example /brand/SVG instead of /SVG

**Comment by RedGuy12** [comment]
fixed in https://github.com/onedotprojects/auth/commit/f9f03f78d504be13266b92ac804f300835bd5aa6
